import { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { recommendationsApi, feedbackApi, playlistsApi } from '../api'
import toast from 'react-hot-toast'

const ACTIVITIES = [
  { id: 'studying', label: 'Studying', icon: '📚', desc: 'Deep learning sessions' },
  { id: 'coding', label: 'Coding', icon: '💻', desc: 'Programming & development' },
  { id: 'reading', label: 'Reading', icon: '📖', desc: 'Books and articles' },
  { id: 'deep_work', label: 'Deep Work', icon: '🎯', desc: 'Focused, uninterrupted work' },
  { id: 'creative_thinking', label: 'Creative', icon: '🎨', desc: 'Brainstorming & design' },
  { id: 'gym_workout', label: 'Gym', icon: '🏋️', desc: 'Weight training' },
  { id: 'running', label: 'Running', icon: '🏃', desc: 'Cardio & running' },
  { id: 'yoga', label: 'Yoga', icon: '🧘', desc: 'Yoga & stretching' },
  { id: 'meditation', label: 'Meditation', icon: '🌿', desc: 'Mindfulness practice' },
  { id: 'sleeping', label: 'Sleeping', icon: '😴', desc: 'Rest & sleep' },
  { id: 'relaxing', label: 'Relaxing', icon: '☕', desc: 'Wind down & chill' },
  { id: 'driving', label: 'Driving', icon: '🚗', desc: 'Commute & road trips' },
]

const OUTCOMES = [
  { id: 'improve_focus', label: 'Improve Focus', icon: '🎯' },
  { id: 'reduce_stress', label: 'Reduce Stress', icon: '🌊' },
  { id: 'boost_energy', label: 'Boost Energy', icon: '⚡' },
  { id: 'improve_mood', label: 'Improve Mood', icon: '😊' },
  { id: 'sleep_better', label: 'Sleep Better', icon: '😴' },
  { id: 'stay_motivated', label: 'Stay Motivated', icon: '🔥' },
  { id: 'feel_calm', label: 'Feel Calm', icon: '🌿' },
  { id: 'feel_energized', label: 'Feel Energized', icon: '✨' },
]

const MOOD_COLOR = {
  stressed: '#EF4444', anxious: '#F97316', burned_out: '#6B7280',
  sleepy: '#8B5CF6', energetic: '#F59E0B', motivated: '#10B981',
  calm: '#06B6D4', focused: '#3B82F6', relaxed: '#84CC16',
}

export default function RecommendationPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const [step, setStep] = useState('select')  // 'select' | 'loading' | 'results'
  const [activity, setActivity] = useState('')
  const [outcome, setOutcome] = useState('')
  const [recommendations, setRecommendations] = useState(null)
  const [expandedTrack, setExpandedTrack] = useState(null)
  const [rating, setRating] = useState(0)
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false)
  const [saving, setSaving] = useState(false)

  const assessmentId = location.state?.assessmentId
  const mood = location.state?.mood

  const handleGenerate = async () => {
    if (!activity) {
      toast.error('Please select an activity')
      return
    }
    setStep('loading')
    try {
      const res = await recommendationsApi.generate({
        assessment_id: assessmentId,
        activity_type: activity,
        desired_outcome: outcome || undefined,
        playlist_length: 20,
      })
      setRecommendations(res.data)
      setStep('results')
      toast.success(`Generated ${res.data.track_count} tracks for you! 🎵`)
    } catch (err) {
      toast.error('Failed to generate recommendations')
      setStep('select')
    }
  }

  const handleRating = async (stars) => {
    setRating(stars)
    if (!recommendations?.session_id) return
    try {
      await feedbackApi.submitSession({
        session_id: recommendations.session_id,
        overall_rating: stars,
        pre_mood: mood,
        feedback_tags: [],
      })
      setFeedbackSubmitted(true)
      toast.success('Thanks for the feedback! 🌟')
    } catch {}
  }

  const handleSavePlaylist = async () => {
    setSaving(true)
    try {
      const activityLabel = ACTIVITIES.find(a => a.id === activity)?.label || activity
      await playlistsApi.create({
        session_id: recommendations.session_id,
        name: `${activityLabel} — ${new Date().toLocaleDateString()}`,
        description: `${mood ? mood.charAt(0).toUpperCase() + mood.slice(1) + ' mood · ' : ''}${activityLabel} playlist generated by MoodSync`,
      })
      toast.success('Playlist saved! 🎵')
    } catch {
      toast.error('Failed to save playlist')
    } finally {
      setSaving(false)
    }
  }

  const formatDuration = (ms) => {
    const min = Math.floor(ms / 60000)
    const sec = Math.floor((ms % 60000) / 1000)
    return `${min}:${sec.toString().padStart(2, '0')}`
  }

  // ── Loading State ──
  if (step === 'loading') {
    return (
      <div className="page-layout" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center', maxWidth: 400 }}>
          <div style={{ fontSize: '4rem', marginBottom: 24, animation: 'float 2s ease-in-out infinite' }}>🎵</div>
          <h2 style={{ marginBottom: 12 }}>Building Your Playlist...</h2>
          <p style={{ color: 'var(--text-muted)', marginBottom: 32 }}>
            Analyzing your mood, applying ISO Principle, ranking tracks by psychological alignment...
          </p>
          <div className="spinner spinner-lg" style={{ margin: '0 auto' }} />
          <div style={{ marginTop: 24, display: 'flex', flexDirection: 'column', gap: 8 }}>
            {['🧠 Classifying psychological state...', '🎯 Fusing mood + activity context...', '✦ Ranking tracks by mood alignment...'].map((step, i) => (
              <div key={i} style={{
                fontSize: '0.8rem', color: 'var(--text-muted)',
                padding: '8px 16px', background: 'rgba(255,255,255,0.03)',
                borderRadius: 8, border: '1px solid rgba(255,255,255,0.05)',
              }}>{step}</div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  // ── Results ──
  if (step === 'results' && recommendations) {
    const profile = recommendations.music_profile
    const moodColor = MOOD_COLOR[recommendations.primary_mood] || 'var(--primary)'

    return (
      <div className="page-layout">
        <div className="main-content">
          {/* Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32, flexWrap: 'wrap', gap: 16 }}>
            <div>
              <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' }}>
                <span style={{
                  background: `${moodColor}20`, color: moodColor,
                  border: `1px solid ${moodColor}40`,
                  padding: '4px 12px', borderRadius: 99,
                  fontSize: '0.8rem', fontWeight: 700,
                }}>
                  {recommendations.primary_mood?.replace('_', ' ')?.toUpperCase()}
                </span>
                <span className="badge badge-primary">
                  {ACTIVITIES.find(a => a.id === recommendations.activity)?.icon} {recommendations.activity?.replace('_', ' ')}
                </span>
              </div>
              <h1 style={{ fontSize: '1.75rem', marginBottom: 8 }}>
                Your Personalized Playlist
              </h1>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                {recommendations.track_count} tracks · Generated in {recommendations.generation_time_ms}ms · ISO Principle Applied
              </p>
            </div>
            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
              <button
                className="btn btn-secondary"
                onClick={handleSavePlaylist}
                disabled={saving}
              >
                {saving ? '...' : '♪ Save Playlist'}
              </button>
              <button
                className="btn btn-ghost"
                onClick={() => setStep('select')}
              >
                ↺ New Search
              </button>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 24, alignItems: 'start' }}>
            {/* Track List */}
            <div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {recommendations.tracks.map((track, idx) => (
                  <div key={track.spotify_id}>
                    <div
                      className="track-card"
                      onClick={() => setExpandedTrack(expandedTrack === track.spotify_id ? null : track.spotify_id)}
                      style={{ cursor: 'pointer' }}
                    >
                      <span className="track-rank">#{track.rank}</span>
                      <img
                        className="track-album-art"
                        src={track.album_art_url || `https://picsum.photos/seed/${idx}/56/56`}
                        alt={track.album}
                        onError={e => { e.target.src = `https://picsum.photos/seed/${idx+5}/56/56` }}
                      />
                      <div className="track-info">
                        <div className="track-title">{track.title}</div>
                        <div className="track-artist">{track.artist} · {track.album}</div>
                        <div style={{ display: 'flex', gap: 8, marginTop: 4, flexWrap: 'wrap' }}>
                          <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                            {formatDuration(track.duration_ms)}
                          </span>
                          <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                            {track.audio_features.tempo.toFixed(0)} BPM
                          </span>
                        </div>
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 6 }}>
                        <div style={{
                          fontSize: '0.75rem', fontWeight: 700,
                          color: track.scores.mood_alignment > 0.75 ? '#10B981' : 'var(--primary-light)',
                        }}>
                          {(track.scores.final_score * 100).toFixed(0)}%
                        </div>
                        <a
                          href={track.spotify_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          onClick={e => e.stopPropagation()}
                          style={{
                            fontSize: '0.7rem', color: '#1DB954',
                            textDecoration: 'none', fontWeight: 600,
                          }}
                        >
                          ▶ Apple Music
                        </a>
                      </div>
                    </div>

                    {/* Expanded explanation */}
                    {expandedTrack === track.spotify_id && (
                      <div style={{
                        margin: '4px 0 8px 40px',
                        padding: '12px 16px',
                        background: 'rgba(124,58,237,0.08)',
                        border: '1px solid rgba(124,58,237,0.2)',
                        borderRadius: '0 0 12px 12px',
                        fontSize: '0.8rem', color: 'var(--text-secondary)',
                        lineHeight: 1.6,
                      }}>
                        <strong style={{ color: 'var(--primary-light)' }}>Why this track: </strong>
                        {track.explanation}
                        <div style={{ display: 'flex', gap: 16, marginTop: 10, flexWrap: 'wrap' }}>
                          {[
                            { label: 'Energy', val: (track.audio_features.energy * 100).toFixed(0) + '%' },
                            { label: 'Valence', val: (track.audio_features.valence * 100).toFixed(0) + '%' },
                            { label: 'Instrumental', val: (track.audio_features.instrumentalness * 100).toFixed(0) + '%' },
                            { label: 'Acoustic', val: (track.audio_features.acousticness * 100).toFixed(0) + '%' },
                          ].map(f => (
                            <div key={f.label} style={{ textAlign: 'center' }}>
                              <div style={{ fontWeight: 700, color: 'var(--primary-light)', fontSize: '0.85rem' }}>{f.val}</div>
                              <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{f.label}</div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Sidebar: Music Profile + Rating */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
              {/* Music Profile Card */}
              <div className="card">
                <div className="section-title" style={{ marginBottom: 16, fontSize: '1rem' }}>Music Profile Used</div>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 16, lineHeight: 1.6 }}>
                  {profile.profile_rationale}
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                  {[
                    { label: 'Tempo', value: `${profile.tempo_range[0].toFixed(0)}–${profile.tempo_range[1].toFixed(0)} BPM` },
                    { label: 'Energy', value: `${(profile.energy_range[0]*100).toFixed(0)}–${(profile.energy_range[1]*100).toFixed(0)}%` },
                    { label: 'Valence', value: `${(profile.valence_range[0]*100).toFixed(0)}–${(profile.valence_range[1]*100).toFixed(0)}%` },
                    { label: 'Instrumental Min', value: `${(profile.instrumentalness_min*100).toFixed(0)}%` },
                  ].map(f => (
                    <div key={f.label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem' }}>
                      <span style={{ color: 'var(--text-muted)' }}>{f.label}</span>
                      <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>{f.value}</span>
                    </div>
                  ))}
                  <hr className="divider" style={{ margin: '8px 0' }} />
                  <div style={{ fontSize: '0.75rem' }}>
                    <div style={{ color: 'var(--text-muted)', marginBottom: 6 }}>Seed Genres:</div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                      {profile.seed_genres.map(g => (
                        <span key={g} className="badge badge-primary" style={{ fontSize: '0.65rem', padding: '2px 8px' }}>
                          {g}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* Rating Card */}
              {!feedbackSubmitted ? (
                <div className="card" style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: '1.5rem', marginBottom: 8 }}>⭐</div>
                  <div className="section-title" style={{ fontSize: '1rem', marginBottom: 8 }}>Rate This Playlist</div>
                  <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 16 }}>
                    Your feedback trains the recommendation engine for better future results.
                  </p>
                  <div className="star-rating" style={{ justifyContent: 'center' }}>
                    {[1,2,3,4,5].map(star => (
                      <button
                        key={star}
                        className={`star ${star <= rating ? 'filled' : 'empty'}`}
                        onClick={() => handleRating(star)}
                        style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '0 2px' }}
                      >
                        {star <= rating ? '★' : '☆'}
                      </button>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="card" style={{ textAlign: 'center', border: '1px solid rgba(16,185,129,0.3)' }}>
                  <div style={{ fontSize: '2rem', marginBottom: 8 }}>✅</div>
                  <p style={{ color: '#6EE7B7', fontSize: '0.85rem' }}>
                    Thanks! Your feedback is improving future recommendations.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    )
  }

  // ── Activity Selection ──
  return (
    <div className="page-layout">
      <div className="main-content" style={{ maxWidth: 800, margin: '0 auto' }}>
        <div style={{ textAlign: 'center', marginBottom: 40 }}>
          <h1 style={{ marginBottom: 12 }}>Find Your Music</h1>
          <p style={{ color: 'var(--text-muted)' }}>
            {mood
              ? `Your mood: ${mood.replace('_', ' ')}. Now select what you're doing.`
              : 'Select your current activity and desired outcome.'}
          </p>
          {!assessmentId && (
            <div style={{
              display: 'inline-block', marginTop: 12,
              background: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.3)',
              borderRadius: 8, padding: '8px 16px', fontSize: '0.8rem', color: '#FCD34D',
            }}>
              💡 Tip: Complete a mood check-in first for better recommendations
            </div>
          )}
        </div>

        {/* Activity Grid */}
        <div style={{ marginBottom: 40 }}>
          <h3 style={{ marginBottom: 20, fontSize: '1.1rem' }}>What are you doing?</h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 12 }}>
            {ACTIVITIES.map(act => (
              <button
                key={act.id}
                onClick={() => setActivity(act.id)}
                style={{
                  padding: '16px 12px',
                  background: activity === act.id ? 'rgba(124,58,237,0.2)' : 'rgba(255,255,255,0.03)',
                  border: activity === act.id ? '1px solid rgba(124,58,237,0.5)' : '1px solid rgba(255,255,255,0.06)',
                  borderRadius: 12, cursor: 'pointer',
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                  transition: 'all 0.2s ease',
                  transform: activity === act.id ? 'scale(1.03)' : 'scale(1)',
                  boxShadow: activity === act.id ? '0 0 20px rgba(124,58,237,0.2)' : 'none',
                }}
              >
                <span style={{ fontSize: '1.75rem' }}>{act.icon}</span>
                <span style={{
                  fontSize: '0.8rem', fontWeight: 600,
                  color: activity === act.id ? 'var(--primary-light)' : 'var(--text-secondary)',
                }}>
                  {act.label}
                </span>
                <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{act.desc}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Outcome Selection */}
        <div style={{ marginBottom: 40 }}>
          <h3 style={{ marginBottom: 20, fontSize: '1.1rem' }}>What do you want to achieve? <span style={{ color: 'var(--text-muted)', fontSize: '0.8rem', fontWeight: 400 }}>(optional)</span></h3>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
            {OUTCOMES.map(out => (
              <button
                key={out.id}
                onClick={() => setOutcome(outcome === out.id ? '' : out.id)}
                className={`btn ${outcome === out.id ? 'btn-primary' : 'btn-ghost'}`}
              >
                {out.icon} {out.label}
              </button>
            ))}
          </div>
        </div>

        <div style={{ textAlign: 'center' }}>
          <button
            className="btn btn-primary btn-lg"
            onClick={handleGenerate}
            disabled={!activity}
            style={{ minWidth: 240 }}
          >
            ✦ Generate My Playlist
          </button>
        </div>
      </div>
    </div>
  )
}
